name: Create BigQuery Table
on:
  push:
    branches: 
      - main
    path:
    - "srcSQL/*"

jobs:
  create-bigquery-table:
    runs-on: ubuntu-latest
    environment: stag  # Environment for clarity (optional)
    permissions:
      contents: read  # Only read permission needed for checkout
      id-token: write  # Needed for Workload Identity

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - id: auth
        uses: google-github-actions/auth@v2  # Updated to latest version
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}  # Use secrets here
          service_account: ${{ vars.SERVICE_ACCOUNT }}  # Use secrets here

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          export_default_credentials: true  # Automatic credential handling 

      - name: Execute SQL file
        run: |  # Changed to multi-line for  readability
          bq query --use_legacy_sql=false --project_id=relevate-dev-403605 "DevOps/srcSQL/CreateDevOpsTestTable.sql"
