name: Create BigQuery Table

on:
  push:
    branches:
      - main
    path:
      - "srcSQL/*"
  workflow_dispatch:

jobs:
  create-bigquery-table:
    runs-on: ubuntu-latest
    environment: stag
    permissions:
      contents: read  # Only read permission  needed for checkout
      id-token: write  # Needed for Workload Identity

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        export_default_credentials: true  # Automatic credential handling

    - name: Execute SQL file
      env:
        gcp_project: ${{ env.PROJECTID }}
        dataset_schema_directory: 'srcSQL/CreateDevOpsTestTable.sql'  # Replace with your schema file path
        credentials: ${{ vars.SERVICE_ACCOUNT }}  # Assuming service account JSON is stored as a secret
