name: Data flow
on:
  push:
    branches: 
      - main
    paths:
      - "DataFlow/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for  all  branches and  tags

  data-flow-template:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: stag   
    permissions:
      contents: read   
      id-token: write   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - id: auth
        uses: google-github-actions/auth@v2  # Updated to latest version
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}  #Use secrets  here 
          service_account: ${{ vars.SERVICE_ACCOUNT }}  # Use secrets here

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          export_default_credentials: true  # Automatic credential  handling   

      - name: Deploy Dataflow Template
        run: |
           gcloud dataflow jobs run relevate-gcs-to-bq-df-3 \
            --gcs-location=gs://relevate-dev-403605-devops2207/dataflow_template/relevate-gcs-to-bq-df-2
            --region=us-central1 \
            --parameters=parameter1=value1,parameter2=value2
