on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_job:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: 'relevate-dev-403605'
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'developer@relevate-dev-403605.iam.gserviceaccount.com'

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: 'Insert_Data_Test_Poc'
          runtime: 'python37'
          project_id: 'relevate-dev-403605'
          entry_point: 'function.Insert_Data_Test_Poc'

      - name: Add IAM policy binding
        run: |
          gcloud functions add-iam-policy-binding Insert_Data_Test_Poc --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: Test deployed function
        run: |
          curl "${{ steps.deploy.outputs.url }}"
