name: CI/CD
on:
  push:
    branches:
      - main
    path:
      - "src/*"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-functions: ${{ steps.detect.outputs.changed-functions }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: get last commit details
        id: last_commit
        run: |
          LAST_COMMIT=$(cat ${{ github.workspace }}/Icf.txt)
          echo "last commit: $LAST_COMMIT"
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_OUTPUT
      - name: Get Last Merge Commit
        id: last_merge
        run: |
          LAST_MERGE=$(git log main --merges -1 --format=%H)
          echo "Last merge commit : $LAST_MERGE"
          echo "LAST_MERGE=$LAST_MERGE" >> $GITHUB_OUTPUT
      - name: Get Previous Merge Commit
        id: prev_merge
        run: |
          PREV_MERGE=$(git log main --merges -2 --format=%H | tail -n 1)
          echo "Previous merge commit: $PREV_MERGE"
          echo "PREV_MERGE=$PREV_MERGE" >> $GITHUB_OUTPUT
      - id: detect
        run: |
          CHANGED_FUNCTIONS=()
          git fetch origin main
          # get changed files
          echo "Previous merge commit: ${{ steps.prev_merge.outputs.PREV_MERGE }}"
          echo "Last merge commit: ${{ steps.last_merge.outputs.LAST_MERGE }}"
          echo "Last commit: ${{ steps.last_commit.outputs.LAST_COMMIT }}"
          CHANGED_FILES=CHANGED_FILES=$(git diff --name-only ${{ steps.last_commit.outputs.LAST_COMMIT }} main)
           
          #get changed dirs
          CHANGED_DIRS=$(for file in $CHANGED_FILES; do dirname $file; done | grep '^src/' | sort | uniq)
          echo "Directories: $CHANGED_DIRS"
          for DIR in $CHANGED_DIRS; do
              if [ "$DIR" = ".github" ] || [ "$DIR" = ".github/workflows" ]; then
                continue
              fi
              echo "Directory name: $DIR"
              FUNCTION_NAME=$(basename $DIR)
              echo "function name: $FUNCTION_NAME"
              # Assuming entry point can be derived from function name
              ENTRY_POINT="${FUNCTION_NAME}"
              CHANGED_FUNCTIONS+=("{\"name\": \"$FUNCTION_NAME\", \"entry_point\": \"$ENTRY_POINT\"}")
          done
          if [ ${#CHANGED_FUNCTIONS[@]} -eq 0 ]; then
            echo "changed-functions=[]" >> $GITHUB_OUTPUT
          else
            CHANGED_FUNCTIONS_JSON=$(printf '[%s]' "$(IFS=,; echo "${CHANGED_FUNCTIONS[*]}")")
            echo "changed-functions=$CHANGED_FUNCTIONS_JSON" >> $GITHUB_OUTPUT
          fi
  deploy-staging:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: stag
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        function: ${{ fromJson(needs.detect-changes.outputs.changed-functions) }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1"
          service_account: "devops-git@relevate-dev-403605.iam.gserviceaccount.com"

      - name: Check_if_Bucket_Exists
        id: check_bucket
        run: |
          BUCKET_NAME="vikas_test_08"
          if gsutil ls -b gs://$BUCKET_NAME; then
             echo "Bucket $BUCKET_NAME exists"
          else
            echo "Bucket $BUCKET_NAME does not exist "
            gcloud storage buckets create gs://$BUCKET_NAME \
            --project relevate-dev-403605 \
            --location us-central1
          fi

      - name: topic
        run: |
          gcloud pubsub topics create vikas-topic-devops

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: ${{ matrix.function.name }}
          runtime: "python312"
          project_id: "relevate-dev-403605"
          entry_point: ${{ matrix.function.entry_point }}
          event_trigger_type: "google.cloud.storage.object.v1.finalized"
          event_trigger_resource: "projects/relevate-dev-403605/locations/us-central1/buckets/devops_poc"
          event_trigger_filters: |-
             bucket= devops_poc
          timeout: "10m"
          source_dir: "src/${{ matrix.function.name }}"

  deploy-dev:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        function: ${{ fromJson(needs.detect-changes.outputs.changed-functions) }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1"
          service_account: "devops-git@relevate-dev-403605.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function.name }}
          runtime: "python312"
          project_id: "relevate-dev-403605"
          entry_point: ${{ matrix.function.entry_point }}
          event_trigger_type: "google.cloud.storage.object.v1.finalized"
          event_trigger_resource: "projects/_/buckets/relevate-dev-403605/sample-files-schema"
          timeout: "10m"
          source_dir: "src/${{ matrix.function.name }}"

  deploy-production:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        function: ${{ fromJson(needs.detect-changes.outputs.changed-functions) }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/265885005616/locations/global/workloadIdentityPools/gitactionprod2506/providers/gitproviderprod2506"
          service_account: "devops-git-prod@relevate-349919.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function.name }}
          runtime: "python312"
          project_id: "relevate-349919"
          entry_point: ${{ matrix.function.entry_point }}
          event_trigger_type: "google.cloud.storage.object.v2.finalized"
          event_trigger_resource: "projects/_/buckets/relevate-dev-403605/sample-files-schema"
          timeout: "10m"
          source_dir: "src/${{ matrix.function.name }}"

  commitwrite:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.email "vikask@contata.in"
          git config --global user.name "Vikas Kumar"
      - name: Get last commit details
        id: last_commit_write
        run: |
          LAST_COMMIT_WRITE=$(git rev-parse HEAD)
          echo "$LAST_COMMIT_WRITE" > ${{ github.workspace }}/Icf.txt
          echo "Last commit hash: $LAST_COMMIT_WRITE"
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Automated commit by CI/CD"
          git push origin main
