name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'devops-git@relevate-dev-403605.iam.gserviceaccount.com'

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: 'Insert_Data_DevOps_git_push'
          runtime: 'python312'
          project_id: 'relevate-dev-403605'
          entry_point: 'Insert_Data_Test_Poc'
          timeout: '10m'
          source_dir: 'DevOpsInsertDataIntoTable'
 