name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run on pushes to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'devops-git@relevate-dev-403605.iam.gserviceaccount.com'

      - name: Deploy to Development (dev) environment
        id: deploy_dev
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: 'Insert_Data_test_GP'
          runtime: 'python312'
          project_id: 'relevate-dev-403605'
          entry_point: 'Insert_Data_test'
          timeout: '10m'
          source_dir: 'DevOpsInsert_test'
        env:
          ENV_VAR_NAME: ${{ secrets.DEV_ENV_VAR }}
