name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: dev
    permissions: 
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'devops-git@relevate-dev-403605.iam.gserviceaccount.com'

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: 'Insert_Data_test_GP_stag'
          runtime: 'python312'
          project_id: 'relevate-dev-403605'
          entry_point: 'Insert_Data_test'
          timeout: '10m'
          source_dir: 'DevOpsInsert_test'

  deploy-production:
    runs-on: ubuntu-latest
    environment: prod
    permissions: 
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/265885005616/locations/global/workloadIdentityPools/gitactionprod2506/providers/gitproviderprod2506'
          service_account: 'devops-git-prod@relevate-349919.iam.gserviceaccount.com'

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: 'Insert_Data_test_GP_prod'
          runtime: 'python312'
          project_id: 'relevate-349919'
          entry_point: 'Insert_Data_test'
          timeout: '10m'
          source_dir: 'DevOpsInsert_test'
