name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-functions: ${{ steps.detect.outputs.changed-functions }}
    steps:
      - uses: actions/checkout@v4

      - id: detect
        run: |
          CHANGED_FUNCTIONS=""
          git fetch origin main
          for DIR in DevOpsInsert_test/Function1; do
            if git diff --name-only origin/main | grep -q "^$DIR/"; then
              FUNCTION_NAME=$(basename $DIR)
              CHANGED_FUNCTIONS="$CHANGED_FUNCTIONS,$FUNCTION_NAME"
            fi
          done
          CHANGED_FUNCTIONS=${CHANGED_FUNCTIONS#,}  # Remove leading comma
          if [ -z "$CHANGED_FUNCTIONS" ]; then
            echo "changed-functions=[]" >> $GITHUB_OUTPUT
          else
            CHANGED_FUNCTIONS_JSON=$(printf '[%s]' "$CHANGED_FUNCTIONS" | sed 's/,/","/g')
            echo "changed-functions=$CHANGED_FUNCTIONS_JSON" >> $GITHUB_OUTPUT
          fi

  deploy-staging:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: dev
    permissions: 
      contents: read
      id-token: write

    strategy:
      matrix:
        function: ${{ fromJson(needs.detect-changes.outputs.changed-functions) }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'devops-git@relevate-dev-403605.iam.gserviceaccount.com'

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function }}
          runtime: 'python312'
          project_id: 'relevate-dev-403605'
          entry_point: 'Insert_Data_test'
          timeout: '10m'
          source_dir: 'DevOpsInsert_test/${{ matrix.function }}'

  deploy-production:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: prod
    permissions: 
      contents: read
      id-token: write

    strategy:
      matrix:
        function: ${{ fromJson(needs.detect-changes.outputs.changed-functions) }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/265885005616/locations/global/workloadIdentityPools/gitactionprod2506/providers/gitproviderprod2506'
          service_account: 'devops-git-prod@relevate-349919.iam.gserviceaccount.com'
          
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function }}
          runtime: 'python312'
          project_id: 'relevate-349919'
          entry_point: 'Insert_Data_test'
          timeout: '10m'
          source_dir: 'DevOpsInsert_test/${{ matrix.function }}'
