name: CI/CD
on:
  push:
    branches:
      - main
    path: 
      - 'src/*'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-functions: ${{ steps.detect.outputs.changed-functions }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: get last commit details
        id: last_commit
        run: |
           LAST_COMMIT=$(cat ${{ github.workspace }}Icf.txt)
           echo "last commit: $LAST_COMMIT"
           echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_OUTPUT

      - name: Get Last Merge Commit
        id: last_merge
        run: |
          LAST_MERGE=$(git log main --merges -1 --format=%H)
          echo "Last merge commit: $LAST_MERGE"
          echo "LAST_MERGE=$LAST_MERGE" >> $GITHUB_OUTPUT

      - name: Get Previous Merge Commit
        id: prev_merge
        run: |
          PREV_MERGE=$(git log main --merges -2 --format=%H | tail -n 1)
          echo "Previous merge commit: $PREV_MERGE"
          echo "PREV_MERGE=$PREV_MERGE" >> $GITHUB_OUTPUT

      - id: detect
        run: |
          CHANGED_FUNCTIONS=()
          git fetch origin main

          # get changed files
          echo "Previous merge commit: ${{ steps.prev_merge.outputs.PREV_MERGE }}"
          echo "Last merge commit: ${{ steps.last_merge.outputs.LAST_MERGE }}"
          CHANGED_FILES=CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $(LAST_COMMIT) | xargs -n 1 src/* | uniq)
           
          #get changed dirs
          CHANGED_DIRS=$(for file in $CHANGED_FILES; do dirname $file; done | sort | uniq)
          echo "Directories: $CHANGED_DIRS"

          for DIR in $CHANGED_DIRS; do
              if [ "$DIR" = ".github" ] || [ "$DIR" = ".github/workflows" ]; then
                continue
              fi
              echo "Directory name: $DIR"
              FUNCTION_NAME=$(basename $DIR)
              echo "function name: $FUNCTION_NAME"
              # Assuming entry point can be derived from function name
              ENTRY_POINT="${FUNCTION_NAME}"
              CHANGED_FUNCTIONS+=("{\"name\": \"$FUNCTION_NAME\", \"entry_point\": \"$ENTRY_POINT\"}")
          done

          if [ ${#CHANGED_FUNCTIONS[@]} -eq 0 ]; then
            echo "changed-functions=[]" >> $GITHUB_OUTPUT
          else
            CHANGED_FUNCTIONS_JSON=$(printf '[%s]' "$(IFS=,; echo "${CHANGED_FUNCTIONS[*]}")")
            echo "changed-functions=$CHANGED_FUNCTIONS_JSON" >> $GITHUB_OUTPUT
          fi

  deploy-staging:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        function: ${{ fromJson(needs.detect-changes.outputs.changed-functions) }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1"
          service_account: "devops-git@relevate-dev-403605.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function.name }}
          runtime: "python312"
          project_id: "relevate-dev-403605"
          entry_point: ${{ matrix.function.entry_point }}
          timeout: "10m"
          source_dir: "src/${{ matrix.function.name }}"

  deploy-production:
    needs: detect-changes
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        function: ${{ fromJson(needs.detect-changes.outputs.changed-functions) }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/265885005616/locations/global/workloadIdentityPools/gitactionprod2506/providers/gitproviderprod2506"
          service_account: "devops-git-prod@relevate-349919.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function.name }}
          runtime: "python312"
          project_id: "relevate-349919"
          entry_point: ${{ matrix.function.entry_point }}
          timeout: "10m"
          source_dir: "src/${{ matrix.function.name }}"

  commitwrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get last commit details
        id: last_commit_write
        run: |
          LAST_COMMIT=$(cat ${{ github.workspace }}/Icf.txt)
          echo "last commit: $LAST_COMMIT"
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_OUTPUT
          git push origin main