name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: relevate-dev-403605

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.PROJECT}}
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: Insert_Data_Test_Poc
          runtime: python 3.12
          project_id: relevate-dev-403605
          entry_point: functions.Insert_Data_Test_Poc

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding Insert_Data_Test_Poc --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"

