name: CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy_job_staging:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'devops-git@relevate-dev-403605.iam.gserviceaccount.com'

      - name: Deploy to Staging
        id: deploy_staging
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: 'Insert_Data_test_GP'
          runtime: 'python312'
          project_id: 'relevate-dev-403605'
          entry_point: 'Insert_Data_test'
          timeout: '10m'
          source_dir: 'DevOpsInsert_test'
          environment:
            Name: 'Dev'

      - name: Deploy to Production
        id: deploy_production
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: 'Insert_Data_test_GP_1'
          runtime: 'python312'
          project_id: 'relevate-349919'
          entry_point: 'Insert_Data_test'
          timeout: '10m'
          source_dir: 'DevOpsInsert_test'
          environment:
            Name: 'prod'
