name: CI/CD and Issue Management

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: 'ubuntu-latest'
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GCP Service Account
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{env.PROJECT}}
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: 'Insert_Data_Test_Poc_CF'
          runtime: 'python312'  
          project_id: 'relevate-dev-403605'
          entry_point: 'function.Insert_Data_Test_Poc'
          timeout: '10m'
          service_account_email: 'devops-git@relevate-dev-403605.iam.gserviceaccount.com'
          source_dir: 'DevOpsInsertDataIntoTable'

  open_issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Deployment Failure on Main Branch" --body "The deployment to the main branch failed during the CI/CD pipeline. Triggered by ${{ github.actor }} with commit message: ${{ github.event.head_commit.message }}."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
