name: CI/CD

on:
  pull_request:
    types: [closed]

jobs:
  detect-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Detect changed functions
        id: detect
        run: |
          CHANGED_FUNCTIONS=()
          git fetch origin main
          for DIR in src/*; do
            if git diff --name-only origin/main | grep -q "^$DIR/"; then
              FUNCTION_NAME=$(basename $DIR)
              ENTRY_POINT="${FUNCTION_NAME}"
              CHANGED_FUNCTIONS+=("{\"name\": \"$FUNCTION_NAME\", \"entry_point\": \"$ENTRY_POINT\"}")
            fi
          done
          if [ ${#CHANGED_FUNCTIONS[@]} -eq 0 ]; then
            echo "::set-output name=changed-functions::[]"
          else
            CHANGED_FUNCTIONS_JSON=$(printf '[%s]' "$(IFS=,; echo "${CHANGED_FUNCTIONS[*]}")")
            echo "::set-output name=changed-functions::$CHANGED_FUNCTIONS_JSON"
          fi

  deploy-staging:
    needs: detect-merge
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'devops-git@relevate-dev-403605.iam.gserviceaccount.com'

      - name: Deploy to dev environment
        id: deploy
        run: |
          for FUNCTION in ${{ steps.detect-merge.outputs.changed-functions }}; do
            NAME=$(echo $FUNCTION | jq -r '.name')
            ENTRY_POINT=$(echo $FUNCTION | jq -r '.entry_point')
            echo "Deploying function $NAME with entry point $ENTRY_POINT"
            # Adjust deployment command as per your requirements
            # Example: google-github-actions/deploy-cloud-functions@main
            # Replace the following line with your deployment command
            echo "Deployment command placeholder"
          done

  deploy-production:
    needs: detect-merge
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/265885005616/locations/global/workloadIdentityPools/gitactionprod2506/providers/gitproviderprod2506'
          service_account: 'devops-git-prod@relevate-349919.iam.gserviceaccount.com'

      - name: Deploy to production environment
        id: deploy
        run: |
          for FUNCTION in ${{ steps.detect-merge.outputs.changed-functions }}; do
            NAME=$(echo $FUNCTION | jq -r '.name')
            ENTRY_POINT=$(echo $FUNCTION | jq -r '.entry_point')
            echo "Deploying function $NAME with entry point $ENTRY_POINT"
            # Adjust deployment command as per your requirements
            # Example: google-github-actions/deploy-cloud-functions@main
            # Replace the following line with your deployment command
            echo "Deployment command placeholder"
          done
