name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: Insert_Data_Test_Poc_1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps:

      - uses: actions/checkout@v4

      - name: Setup GCP Service Account
        uses: google-github-actions/auth@v2
        with:
          project_id: 'relevate-dev-403605'
          workload_identity_provider: 'projects/580005102993/locations/global/workloadIdentityPools/testpool1/providers/testprovider1'
          service_account: 'developer@relevate-dev-403605.iam.gserviceaccount.com'

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: Insert_Data_Test_Poc
          runtime: java11
          project_id: mkdevyoutube
          entry_point: functions.Insert_Data_Test_Poc

